version: '3'

vars:
  BINARY_NAME: blog_api

dotenv: ['.env']

tasks:
  build:
    cmds:
      - go build -C cmd/app -o ../../.bin/{{.BINARY_NAME}}
  
  run: 
    cmds:
      - task: build
      - ./.bin/{{.BINARY_NAME}}
  
  test:
    cmds:
      - task: build
      - go test -v ./...
